---
rbenv:
  env: user
  version: v1.1.2
  default_ruby: 2.6.3
  rubies:
    - version: 2.6.3

rbenv_users: [vagrant]
rbenv_owner: 'vagrant'

# PostgreSQL
postgresql_version: 11
postgresql_encoding: 'UTF-8'

postgresql_users:
  - name: user_player_statistics
    encrypted: yes
    pass: 123456

postgresql_databases:
  - name: player_statistics
    owner: user_player_statistics
  - name: player_statistics_test
    owner: user_player_statistics

postgresql_user_privileges:
  - name: user_player_statistics
    db: player_statistics
    priv: "ALL"
    role_attr_flags: "SUPERUSER"
  - name: user_player_statistics
    db: player_statistics_test
    priv: "ALL"
    role_attr_flags: "SUPERUSER"

postgresql_listen_addresses:
  - '*'

postgresql_database_extensions:
  - db: player_statistics
    extensions:
      - pg_trgm

  - db: player_statistics_test
    extensions:
      - pg_trgm
